# Pratique

## 1. Import numpy as np and see the version

In [2]:
import numpy as np

print(np.__version__)

2.2.6


## 2. How to create a boolean array? ( Create a 3×3 numpy array of all True’s)

In [7]:
# method 1
boolArr = np.ones([3,3], dtype=bool)
print(boolArr)
print('------')

# Method 2
boolArr = np.full((3,3), False)
print(boolArr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
------
[[False False False]
 [False False False]
 [False False False]]


## 3. How to extract items that satisfy a given condition from 1D array?



 Input -> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 
 Output -> [1, 3, 5, 7, 9]


In [22]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
c = arr[1:10:2]
print(c)
print('------')
print(arr[arr % 2 == 1])

[1 3 5 7 9]
------
[1 3 5 7 9]


# 4. How to replace items that satisfy a condition with another value in numpy array?


#Replace all odd numbers in arr with -1 without changing arr

#Input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#Output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [26]:
out = arr[:]
out[c] = -1
print(out)
print('-------')

arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(out)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
-------
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# 5. How to reshape an array?


Convert a 1D array to a 2D array with 2 rows

Input: a = np.arange(10)

In [36]:
a = np.arange(10)
print(a.reshape(2,-1))

[[0 1 2 3 4]
 [5 6 7 8 9]]


## 6. How to stack two arrays vertically?


Stack arrays a and b vertically

Input: 

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

In [41]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(np.vstack([a,b]))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
