In [113]:
# import resources
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import iqr
import statistics

amir_deals = pd.read_csv('amir_deals.csv')
food_consumption = pd.read_csv('food_consumption.csv')
world_happiness = pd.read_csv('world_happiness.csv')

# Sampling a dataframe

In [114]:
food_consumption.sample()

,Unnamed: 0,country,food_category,consumption,co2_emission
948,949,Grenada,beef,3.46,106.77


In [115]:
# Set a seeding so the operation can be repeated and still give the result
np.random.seed(999170)
food_consumption.sample()

,Unnamed: 0,country,food_category,consumption,co2_emission
610,611,Romania,eggs,12.94,11.89


In [116]:
# pick mutiple elements
np.random.seed(29)
food_consumption.sample(4)

,Unnamed: 0,country,food_category,consumption,co2_emission
572,573,Ecuador,pork,14.44,51.11
10,11,Argentina,nuts,0.49,0.87
697,698,Pakistan,fish,1.87,2.99
1177,1178,Ethiopia,pork,0.02,0.07


# Sampling with/without replacement

In [117]:
# with replacement: independant events
amir_deals.sample(5, replace=True)

,Unnamed: 0,product,client,status,amount,num_users
114,115,Product A,Current,Won,3371.70,18
121,122,Product B,Current,Won,4831.73,12
129,130,Product B,Current,Won,6509.25,53
136,137,Product B,Current,Won,2924.29,32
61,62,Product D,Current,Won,6733.62,27


In [118]:
# without replacement
amir_deals.sample(5)

,Unnamed: 0,product,client,status,amount,num_users
48,49,Product C,Current,Lost,3727.66,19
124,125,Product C,Current,Won,482.01,65
172,173,Product D,Current,Lost,3086.88,55
65,66,Product B,New,Lost,2746.79,50
139,140,Product B,Current,Won,4566.61,9


# Law of large sample

As the size of the sample increase the more the mean is closed to the expected value

# Uniform distribution in python

In [119]:
from scipy.stats import uniform

# P(waiting time >= 7) = uniform.cdf(7,0,12)
# Where 12 represent the uniform time
uniform.cdf(7,0,12)

np.float64(0.5833333333333334)

In [120]:
help(uniform.cdf)

Help on method cdf in module scipy.stats._distn_infrastructure:

cdf(x, *args, **kwds) method of scipy.stats._continuous_distns.uniform_gen instance
    Cumulative distribution function of the given RV.
    
    Parameters
    ----------
    x : array_like
        quantiles
    arg1, arg2, arg3,... : array_like
        The shape parameter(s) for the distribution (see docstring of the
        instance object for more information)
    loc : array_like, optional
        location parameter (default=0)
    scale : array_like, optional
        scale parameter (default=1)
    
    Returns
    -------
    cdf : ndarray
        Cumulative distribution function evaluated at `x`



In [121]:
# P(4 <= waiting time <= 7)= P(waiting time >= 7) - P(waiting time >=4)
uniform.cdf(7,0,12) - uniform.cdf(4,0,12)

np.float64(0.25000000000000006)

# generating random number according to unifor,m distribution

In [122]:
# generating random number according to unifor,m distribution
rdUnifDist = uniform.rvs(size=2, loc=3, scale=5)
rdUnifDist

array([5.02815484, 5.42377734])

In [123]:
rdUnifDist2 = uniform.rvs(0, 5, 10)
rdUnifDist2

array([3.42793099, 1.41050976, 1.77409381, 0.92904293, 1.49526292,
       1.53121433, 2.39630312, 2.05895791, 1.04475923, 1.3061125 ])

In [124]:
help(uniform.rvs)

Help on method rvs in module scipy.stats._distn_infrastructure:

rvs(*args, **kwds) method of scipy.stats._continuous_distns.uniform_gen instance
    Random variates of given type.
    
    Parameters
    ----------
    arg1, arg2, arg3,... : array_like
        The shape parameter(s) for the distribution (see docstring of the
        instance object for more information).
    loc : array_like, optional
        Location parameter (default=0).
    scale : array_like, optional
        Scale parameter (default=1).
    size : int or tuple of ints, optional
        Defining number of random variates (default is 1).
    random_state : {None, int, `numpy.random.Generator`,
                    `numpy.random.RandomState`}, optional
    
        If `random_state` is None (or `np.random`), the
        `numpy.random.RandomState` singleton is used.
        If `random_state` is an int, a new ``RandomState`` instance is
        used, seeded with `random_state`.
        If `random_state` is already a `

# Binomial distribution distribution

## 1. Fixed number of trials
## 2. Two possible outcome par trial
## 3. Each trial is indepent
## If n is the number of trials (integer) and p the probability of success then:
***mean = n * p***

***variance = n * p * (1 - p)*** 

## randomly flipping one or multiples coins 1 or many time

In [125]:
# filling a coin with 50% of change ot succeed 1 times
from scipy.stats import binom

number_of_coins = 1
probability_of_success = 0.5
number_of_time= 1

binom.rvs(number_of_coins, probability_of_success, size=number_of_time)

array([0])

In [126]:
# filling a coin with 50% of change ot succeed 10 times
from scipy.stats import binom

number_of_coins = 1
probability_of_success = 0.5
number_of_time= 10

binom.rvs(number_of_coins, probability_of_success, size=number_of_time)

array([0, 1, 1, 1, 0, 1, 0, 0, 1, 0])

In [127]:
# filling 10 coins with 2% of change ot succeed 1 times
from scipy.stats import binom

number_of_coins = 10
probability_of_success = 0.02
number_of_time= 1

binom.rvs(number_of_coins, probability_of_success, size=number_of_time)

array([0])

In [128]:
# filling 7 coins with 35% of change of succeed 4 times
from scipy.stats import binom

number_of_coins = 7
probability_of_success = 0.35
number_of_time= 3

binom.rvs(number_of_coins, probability_of_success, size=number_of_time)

array([3, 2, 3])

# getting exactly 4 success out of 7 trials (pmf: probability mass function)

In [129]:
probability_of_success = 0.5
number_of_success = 4,
number_of_trials = 70

binom.pmf(number_of_success, number_of_trials, probability_of_success)

array([7.76640274e-16])

#### just testing cdf uniform

In [130]:
from scipy.stats import uniform

p7 = uniform.cdf(7,0, 12)
p4 =uniform.cdf(4,0,12)

r = p7 - p4

r3 = 1-p7

r2 = uniform.cdf(12, 7, 12)

print(f"r: {r} \nr2: {r2}\nr3: {r3}" )

r: 0.25000000000000006 
r2: 0.4166666666666667
r3: 0.41666666666666663
