# Introduction to Python
Run the hidden code cell below to import the data used in this course.

In [2]:
import numpy as np
import pandas as pd

In [3]:
# Importing course packages; you can add more too!
import math

# Import columns as numpy arrays
baseball_names = np.genfromtxt(
    fname="baseball.csv",  # This is the filename
    delimiter=",",  # The file is comma-separated
    usecols=0,  # Use the first column
    skip_header=1,  # Skip the first line
    dtype=str,  # This column contains strings
)
baseball_heights = np.genfromtxt(
    fname="baseball.csv", delimiter=",", usecols=3, skip_header=1
)
baseball_weights = np.genfromtxt(
    fname="baseball.csv", delimiter=",", usecols=4, skip_header=1
)
baseball_ages = np.genfromtxt(
    fname="baseball.csv", delimiter=",", usecols=5, skip_header=1
)

soccer_names = np.genfromtxt(
    fname="fifa.csv",
    delimiter=",",
    usecols=1,
    skip_header=1,
    dtype=str,
    encoding="utf", 
)
soccer_ratings = np.genfromtxt(
    fname="fifa.csv",
    delimiter=",",
    usecols=2,
    skip_header=1,
    encoding="utf", 
)
soccer_positions = np.genfromtxt(
    fname="fifa.csv",
    delimiter=",",
    usecols=3,
    skip_header=1,
    encoding="utf", 
    dtype=str,
)
soccer_heights = np.genfromtxt(
    fname="fifa.csv",
    delimiter=",",
    usecols=4,
    skip_header=1,
    encoding="utf", 
)
soccer_shooting = np.genfromtxt(
    fname="fifa.csv",
    delimiter=",",
    usecols=8,
    skip_header=1,
    encoding="utf", 
)

## Take Notes

Add notes about the concepts you've learned and code cells with code you want to keep.

_Add your notes here_

Find in the hidden cell below some exercises to explore the data and practice your skills:

## Explore Datasets
Use the arrays imported in the first cell to explore the data and practice your skills!
- Print out the weight of the first ten baseball players. 
- What is the median weight of all baseball players in the data? 
- Print out the names of all players with a height greater than 80 (heights are in inches). 
- Who is taller on average? Baseball players or soccer players? Keep in mind that baseball heights are stored in inches!
- The values in `soccer_shooting` are decimals. Convert them to whole numbers (e.g., 0.98 becomes 98).
- Do taller players get higher ratings? Calculate the correlation between `soccer_ratings` and `soccer_heights` to find out!
- What is the average rating for attacking players (`'A'`)?

In [ ]:

baseballPlayers = pd.read_csv("baseball.csv")
soccers = pd.read_csv("fifa.csv")
# print(soccers.head(2))

# Print out the weight of the first ten baseball players
print("the weight of the first ten baseball players\n", baseballPlayers.head(10)['Weight'])

# What is the median weight of all baseball players in the data? 
median_weight = baseballPlayers['Weight'].median()
print("\nthe median weight of all baseball players in the data\n", median_weight)

# Print out the names of all players with a height greater than 80 (heights are in inches). 
print("\nthe names of all players with a height greater than 80\n", baseballPlayers[baseballPlayers['Height'] > 80]['Name'])

# Who is taller on average? Baseball players or soccer players? Keep in mind that baseball heights are stored in inches!
soccersMedianHeight = soccers[' height'].median()
baseballMedianHeight = baseballPlayers['Height'].median()
print(soccersMedianHeight)
print(baseballMedianHeight*2.5) # still have to check conversion from inches to cm
print('On average baseball players are taller')

# The values in `soccer_shooting` are decimals. Convert them to whole numbers (e.g., 0.98 becomes 98).
soccers[' shooting']*100
print(soccers[' shooting'])
# Do taller players get higher ratings? Calculate the correlation between `soccer_ratings` and `soccer_heights` to find out!
soccersCorr = soccers[soccers[' height']> 175][[' rating', ' height']].corr()
b = soccersCorr > 0.5 
result = ""
print(soccersCorr)
print('\nNo taller player does not have higher rating because the correlation between the height and the rating  is 0.036496')

# What is the average rating for attacking players (`'A'`)?
print("\nthe average rating for attacking players\n", soccers[soccers[' position'] == ' A'][' rating'].median())

the weight of the first ten baseball players
 0    180
1    215
2    210
3    210
4    188
5    176
6    209
7    200
8    231
9    180
Name: Weight, dtype: int64

the median weight of all baseball players in the data
 200.0

the names of all players with a height greater than 80
 59         Andrew_Sisco
558       Randy_Johnson
764    Mark_Hendrickson
862         Chris_Young
909           Jon_Rauch
Name: Name, dtype: object
182.0
185.0
On average baseball players are taller
0          
1        65
2        54
3        38
4        64
       ... 
8842     73
8843     78
8844     40
8845     48
8846     56
Name:  shooting, Length: 8847, dtype: object
          rating    height
rating  1.000000  0.036496
height  0.036496  1.000000

No taller player does not have higher rating because the correlation between the height and the rating  is 0.036496

the average rating for attacking players
 67.0


In [60]:
import numpy as np
a= [1,3,5,-6,78,-8,9,0,-56,-69,-73]
b= [90,83,6, -34,0,0,123,456,90,2,5]
x = np.array(a)
y = np.array(b)
z = x+y
t= z**4
print(z)
print(z//2)
print((z/2))
z.shape


[ 91  86  11 -40  78  -8 132 456  34 -67 -68]
[ 45  43   5 -20  39  -4  66 228  17 -34 -34]
[ 45.5  43.    5.5 -20.   39.   -4.   66.  228.   17.  -33.5 -34. ]


(11,)

In [ ]:
e = np.array([t,z,x,y,x+z,y-t])
print("np array shape: ", e.shape)
print("the row we are going to manipulate (e[1]):\n", e[1])
print("\nMean:\n", e[1].sum()/e[1].size)
print("\nMean:\n", np.mean(e[1]))
print("\nMedian:\n", np.median(e[1]))
print("\nCorrelation coefficient of e[1] and e[2]:\n", np.corrcoef(e[1], e[2]))
print("\nCorrelation of row ", np.correlate(e[1],e[2],))
print("\nSorting:", e[1].sort())




np array shape:  (6, 11)
the row we are going to manipulate (e[1]):
 [ 91  86  11 -40  78  -8 132 456  34 -67 -68]

Mean:
 64.0909090909091

Mean:
 64.0909090909091

Median:
 34.0

Correlation coefficient of e[1] and e[2]:
 [[1.         0.36907129]
 [0.36907129 1.        ]]

Correlation of row  [15663]

Sorting: None


In [12]:
# generate numpy data

numpy_array = np.round(np.random.randint(-10000,90870,[800000,10]))
numpy_array1 = np.round(np.random.normal(-10000,90870,[800000,10]),3)

In [13]:
print(np.mean(numpy_array[:,2]))
print(np.median(numpy_array[:,2]))
print(numpy_array1)


40404.03793125
40365.0
[[ -51288.702  -11261.928   46994.405 ...   41843.127  -33608.308
    12001.27 ]
 [ -10115.614  -58526.215   48870.308 ...  -36252.382 -121741.567
    17735.482]
 [   6800.883  135335.646   42465.053 ...   82089.706   27542.104
    46447.989]
 ...
 [ -63893.85    89570.676    7029.544 ...   75429.655   49241.204
   147872.283]
 [  35402.614  -92252.012   45583.649 ...  135269.36   151305.68
   -51430.134]
 [ -66364.715  -21198.074  111933.846 ...   31681.024 -109200.505
    97429.119]]
